ssh-hpc:
	ssh s251750@login.hpc.dtu.dk
upload-hpc: 
	scp -i ~/.ssh/id_rsa hello.py s251750@transfer.gbar.dtu.dk:/zhome/3b/0/221496/Documents/
download-hpc:
	scp -i ~/.ssh/id_rsa s251750@transfer.gbar.dtu.dk:/zhome/3b/0/221496/Documents/hello.py .	
